name = "oxnoc"
version = "1.0.0"

[dependencies]
gleam_stdlib = ">= 0.44.0 and < 2.0.0"
oxcore = { path = "../oxcore" }
oxion_policy = { path = "../../packages/policy" }

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
